version: 0.0
os: linux
files:
  - source: app/
    destination: /var/www/html/

permissions:
  - object: scripts/start_server.sh
    mode: 755

hooks:
  AfterInstall:
    - location: app/scripts/restart_apache.sh
      timeout: 300
      runas: root
