name: Manually Trigger AWS CodePipeline

on:
  push:
    branches:
      - main  #  Change to your branch if not using 'main'

permissions:
  id-token: write
  contents: read

jobs:
  start-codepipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::176387410897:role/GitHubActionsTriggerPipelineRole
          aws-region: ap-south-1  # Use your region

      - name: Start AWS CodePipeline Execution
        run: |
          aws codepipeline start-pipeline-execution --name suchita-codepipeline-pipeline  #  Replace with your pipeline name
